// This is the root layout component for your Next.js app.
// Learn more: https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts#root-layout-required

import { IBM_Plex_Sans } from 'next/font/google'
import { Arimo } from 'next/font/google'
import "./globals.css"
// import '../styles/styles.css'

const ibm_plex_sans = IBM_Plex_Sans({
  weight: ['400', '700'], // 폰트 두께를 지정합니다
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ibm_plex_sans',
})
const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arimo',
})

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={ibm_plex_sans.variable + ' ' + arimo.variable}>
        {children}
      </body>
    </html>
  )
}


// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
